server:
  port: 10000
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
      force: true

#打开actuator的所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"